name: build-and-test-differential

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - labeled

env:
  CC: /usr/lib/ccache/gcc
  CXX: /usr/lib/ccache/g++
#  DOCKER_RUN: docker run --shm-size 1G \
#    -v ${{ github.workspace }}:/workspace \
#    -w /workspace

jobs:
  build-and-test-differential:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        rosdistro:
          - humble
        container-suffix:
          - -cuda
        include:
          - rosdistro: humble
            container: ghcr.io/autowarefoundation/autoware:latest-prebuilt
            build-depends-repos: build_depends.repos
    steps:
      - name: Set PR fetch depth
        run: echo "PR_FETCH_DEPTH=$(( ${{ github.event.pull_request.commits }} + 1 ))" >> "${GITHUB_ENV}"

      - name: Checkout PR branch and all PR commits
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: ${{ env.PR_FETCH_DEPTH }}

      - name: Show disk space before the tasks
        run: df -h

      - name: Show current dir
        run: ls -alF

      - name: Show env vars
        run: printenv

      - name: tree
        run: tree $HOME

      - name: Remove exec_depend
        uses: autowarefoundation/autoware-github-actions/remove-exec-depend@v1

      - name: Get modified packages
        id: get-modified-packages
        uses: ./.github/actions/get-modified-packages-docker
#        with:
#          docker-run: ${{ env.DOCKER_RUN }}
#      - name: docker run
#        run: docker run --shm-size 1G \
#          -v ${{ github.workspace }}:/workspace \
#          -w /workspace \
#          ${{ matrix.container }}${{ matrix.container-suffix }} \
#          /bin/bash -c \

#      - name: Docker
#        run: |
#          docker pull ${{ matrix.container }}${{ matrix.container-suffix }}
#          docker run -it ${{ matrix.container }}${{ matrix.container-suffix }} /bin/bash
